

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ormgpt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: War@123PG
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  db2:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: War@123MS
      MYSQL_DATABASE: ormgpt
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql

  app:
    build: .  # Build from the Dockerfile in the current directory
    environment:
      NODE_ENV: production
      POSTGRES_HOST: db
      MYSQL_HOST: db2
      HUGGING_FACE_API_KEY: your-hugging-face-api-key
    ports:
      - "3000:3000"  # Exposing port 3000 (make sure your app binds to this port)
    depends_on:
      - db
      - db2
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    command: ["npm", "start"]
    expose:
      - "3000"
